language: generic

services:
 - docker

script:

 - docker exec flask/docker-flask pytest ./puppycompanyblog/test.py

before_install:
 - docker build -t flask/docker-flask -f Dockerfile .
 - docker run -d -p 80:80 --name flask/docker-flask flask/docker-flask
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push flask/docker-flask

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "elasticbeanstalk-us-east-2-039283364413"
  bucket_path: "multi-docker"
  on:
    branch: master
