sudo: required
services:
 - docker
language: python

before_install:
 - docker build -t flask/docker-flask -f Dockerfile . 

script:
 - docker exec flask/docker-flask pytest ./company/core/test.py -- --coverage
