language: generic

services:
 - docker

script:

 - docker ps -a 

before_install:
 - docker build -t asengame/flask-docker .
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push asengame/flask-docker

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-flask
  env: Dockerflask-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "elasticbeanstalk-us-east-2-039283364413"
  bucket_path: "multi-docker"
  on:
    branch: master
