{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
    "docker"
  ],
  "before_install": [
    "docker build -t flask/docker-flask -f Dockerfile ."
  ],
  "script": [
    "docker exec flask/docker-flask pytest ./company/core/test.py"
  ],
  "deploy": [
    {
      "provider": "elasticbeanstalk",
      "edge": true,
      "access_key_id": "$AWS_ACCESS_KEY",
      "secret_access_key": "$AWS_SECRET_KEY",
      "region": "us-east-2",
      "app": "multi-docker",
      "env": "Multidocker-env",
      "bucket_path": "docker-multi",
      "on": {
        "branch": [
          "master"
        ]
      },
      "bucket": "elasticbeanstalk-us-east-2-039283364413"
    }
  ]
}
