version: '3'
services:
 redis-server:
  image: redis:6.2-alpine
  environment:
   - REDIS_HOST=redis-server
   - REDIS_PORT=6379
 web:
  image: asengame/flask-docker
  ports:
    - "80:80"
  depends_on:
    - db
    - redis-server
 db:
  image: postgres:12.7-alpine
  environment:
    POSTGRES_DB: flask_db
    POSTGRES_USER: flask_db_admin
    POSTGRES_PASSWORD: asengame
  ports:
    - "5432:5432"

