version: '3'
services:
 redis-server:
  image: redis:6.2-alpine
  environment:
   - REDIS_HOST=redis-server
   - REDIS_PORT=6379
 web:
  image: asengame/flask-docker
  ports:
    - "80:80"
 db:
  image: postgres:12.7-alpine
  environment:
    POSTGRES_DB: postgres_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: asengame
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/psql/data:/var/lib/psql/data 
